### ISSUE TITLE
How to align 3D model to image? 

### ISSUE THREAD

**Issue by jinyu121** [xingyuansun/pix3d#2]
Hi~

This repo provides the render code, but the blende is like a black-box.

Assume that we have the sample points, how can we align the points to the image? Can you share the align code?

THX

**Comment by xingyuansun** [comment]
Thanks for asking. We project point `(x, y, z)` into image coordinate `(u, v)` by the following equation:
![image](https://user-images.githubusercontent.com/16166192/46240629-73238680-c378-11e8-9b29-bd346f2d0cd0.png)
where `f` corresponds to `focal_length` (actually, we provided focal length in mm with the width of the sensor fixed to 32mm (as we mentioned [here](https://github.com/xingyuansun/pix3d#dataset)), and you may need to convert it into focal length in pixels), `R` corresponds to `rot_mat`, `T` corresponds to `trans_mat`, and `(w, h)` correspond to `img_size`. Also notice that for the 3D model, we define `+x` as leftward, `+y` as upward, and `+z` as inward in canonical view, so that `+u` will be leftward (as `+x`) and `+v` will be upward (as `+y`).

A sample code is here.
```python
def project(data, x, y, z):
    import numpy as np
    p_3d = np.array([[x], [y], [z], [1.]])
    RT = np.append(data['rot_mat'], np.resize(data['trans_mat'], [3, 1]), axis=1)
    # Here we convert focal length in mm into focal length in pixels.
    f_pix = data['focal_length'] / 32. * data['img_size'][0]
    K = np.array([[f_pix, 0., data['img_size'][0] / 2.], [0, f_pix, data['img_size'][1] / 2.], [0., 0., 1.]])
    p_2d = np.dot(np.dot(K, RT), p_3d)
    p_2d = p_2d / p_2d[2]
    # Convert u, v into conventional image coordinates (from +u: leftward, +v: upward to +u: rightward, +v: downward).
    p_2d = data['img_size'] - p_2d[:2, 0]
    return p_2d
```

You may find more information in *3.2. Image-Shape Alignment* in our [paper](http://pix3d.csail.mit.edu/papers/pix3d_cvpr.pdf) and [here](https://en.wikipedia.org/wiki/3D_projection#Perspective_projection) in Wikipedia.

**Comment by AlexsaseXie** [comment]
> Thanks for asking. We project point `(x, y, z)` into image coordinate `(u, v)` by the following equation:
> ![image](https://user-images.githubusercontent.com/16166192/46240629-73238680-c378-11e8-9b29-bd346f2d0cd0.png)
> where `f` corresponds to `focal_length` (actually, we provided focal length in mm with the width of the sensor fixed to 32mm (as we mentioned [here](https://github.com/xingyuansun/pix3d#dataset)), and you may need to convert it into focal length in pixels), `R` corresponds to `rot_mat`, `T` corresponds to `trans_mat`, and `(w, h)` correspond to `img_size`. Also notice that for the 3D model, we define `+x` as leftward, `+y` as upward, and `+z` as inward in canonical view, so that `+u` will be leftward (as `+x`) and `+v` will be upward (as `+y`).
> 
> A sample code is here.
> 
> ```python
> def project(data, x, y, z):
>     import numpy as np
>     p_3d = np.array([[x], [y], [z], [1.]])
>     RT = np.append(data['rot_mat'], np.resize(data['trans_mat'], [3, 1]), axis=1)
>     # Here we convert focal length in mm into focal length in pixels.
>     f_pix = data['focal_length'] / 32. * data['img_size'][0]
>     K = np.array([[f_pix, 0., data['img_size'][0] / 2.], [0, f_pix, data['img_size'][1] / 2.], [0., 0., 1.]])
>     p_2d = np.dot(np.dot(K, RT), p_3d)
>     p_2d = p_2d / p_2d[2]
>     # Convert u, v into conventional image coordinates (from +u: leftward, +v: upward to +u: rightward, +v: downward).
>     p_2d = data['img_size'] - p_2d[:2, 0]
>     return p_2d
> ```
> 
> You may find more information in _3.2. Image-Shape Alignment_ in our [paper](http://pix3d.csail.mit.edu/papers/pix3d_cvpr.pdf) and [here](https://en.wikipedia.org/wiki/3D_projection#Perspective_projection) in Wikipedia.

I think the K mat here is kind of incorrect. Basically we should assume that each pixel has equal height and width. So the K mat should be:
```python
    f_pix = data['focal_length'] / 32.
    K = np.array([
         [f_pix * data['img_size'][0], 0, data['img_size'][0] / 2.],
         [0, f_pix * data['img_size'][1], data['img_size'][1] / 2.],
         [0, 0, 1.]
    ])
```

While the calibrated camera parameters in pix3d dataset seem to be under the assumption of above K mat in the quote. I think this will hurt the performance of camera parameters related methods especially with input images that have width/height ratio far from 1.

The following images show the correspondence of 2D keypoints and projected 3D keypoints.
2D keypoints:
![00_2d_keypoint](https://user-images.githubusercontent.com/26740167/104295046-f1c97100-54fa-11eb-9a33-e98a3d95bb41.png)

3D keypoints using author's K mat:
![00_3d_keypoint_authors_K](https://user-images.githubusercontent.com/26740167/104295075-faba4280-54fa-11eb-9f1f-b72250ce21e5.png)

3D keypoints using common K mat:
![00_3d_keypoint_correct_K](https://user-images.githubusercontent.com/26740167/104295127-073e9b00-54fb-11eb-8584-17df265051b6.png)
