### ISSUE TITLE
Rotating a model so it matches the view

### ISSUE THREAD

**Issue by JeremyFisher** [xingyuansun/pix3d#21]
Hi, 

thanks for releasing the dataset, great work!

I have a simple question about rotating a model so that it matches a corresponding view.

Concretely, if I have a model id 1766, image `img/chair/0412.jpg`:
![0412](https://user-images.githubusercontent.com/2420045/108542819-84bcae80-72e4-11eb-91a0-d8046030e02e.jpg)

what should I do to rotate the model `model/chair/SS_042/model.obj`:
![model](https://user-images.githubusercontent.com/2420045/108542938-a9188b00-72e4-11eb-8cc5-b99793aad693.png)

so that it matches the view? I would like to rotate it so that it looks roughly like:
![model_aligned](https://user-images.githubusercontent.com/2420045/108543017-c3eaff80-72e4-11eb-90a2-691ec06b86ee.png)

Thanks

**Comment by xingyuansun** [comment]
Thank you for using Pix3D! Note that merely rotating the object would not necessarily result in the same view since the camera does not always look at the object's center. For a fixed camera, we also have to translate the object. You may refer to [this](https://github.com/xingyuansun/pix3d/issues/2) to align a 3D model to an image and [this](https://github.com/xingyuansun/pix3d#rendering-demo) for rendering. On the other hand, if you assume that the camera is looking at the object's center and only need an approximation, you may use `cam_position` and `inplane_rotation`, as illustrated [here](https://github.com/xingyuansun/pix3d#notice). Thank you!
