### ISSUE TITLE
Inplane Rotation

### ISSUE THREAD

**Issue by YoungXIAO13** [xingyuansun/pix3d#9]
Hi xingyuan,

Since I'm evaluating my viewpoint estimation network on pix3d. I'm wondering how you handle the images containing the huge rotation such as "**/chair/1119**". The azimuth and elevation can still be estimated directly from these images or you have rotated these images before testing?

**Comment by xingyuansun** [comment]
Thanks for asking. We did not rotate these images before testing.

Best,
Xingyuan

**Comment by YoungXIAO13** [comment]
Thanks for your answering, about the annotations, I'm also wondering how you get the camera position and inplane rotation from the rotation matrix. Are you doing euler angles from rotation matrix?

**Comment by ztzhang** [comment]
Hi, to derive the camera position and in-plane rotation, we assume that after cropping/affine transformation, the camera is looking at the object's center. Then, since the keypoint annotation would give the object's position in camera coordinate, the object's translation vector would give the camera position. Then, the object's rotation matrix(pose) is decomposed into an inplane-rotation matrix right multiplied by azimuth-elevation matrix. As the azimuth-elevation matrix is given by the camera position vector, the inplane rotation matrix can therefore be derived.

**Comment by LittleYuer** [comment]
Hi, @ztzhang 

Thanks for explanation.

May I ask does that mean Rot = R(azi)*R(ele)*R(inp) is established on a particular Euler coordinate system given ele(-pi/2, pi/2), azi(-pi, pi), inplane(-pi,pi)? And may I ask which Euler coordinate system?

Thanks for help.

Yuer
